// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Huang Zhaobin
//! The KataGo analysis config mirai writes for itself.
//!
//! `katago analysis` refuses to start without a `-config` file, but only three keys in it
//! are actually required — `numAnalysisThreads`, `numSearchThreadsPerAnalysisThread` and
//! `nnMaxBatchSize`. Everything else either travels on the query, is forced through
//! `-override-config`, or is better left at KataGo's own default so that upstream
//! improvements arrive without mirai having to track them.
//!
//! So mirai generates that file instead of asking the user for one. There is exactly one
//! set of defaults, [`EngineTuning::default`]; nothing is detected or measured at runtime.
//! They are a good starting point on a mid-range GPU, not an optimum for every machine,
//! which is why every value is editable in Preferences.
//!
//! `nnCacheSizePowerOfTwo` is the one key set for a reason other than being required.
//! KataGo's default *for the analysis engine* is 2^23, chosen for the batch-server use the
//! engine was written for: the table is `2^N` entries that fill and then evict, at about
//! 3 KiB each with ownership, so it settles around 24 GiB and costs 128 MiB of pointers
//! before a single query. 2^20 — KataGo's own GTP default — settles around 3 GiB for
//! 16 MiB of pointers, which is the right shape for a desktop sharing the machine. A cache
//! miss only costs a re-evaluation.

use std::io;
use std::path::{Path, PathBuf};

/// The KataGo keys mirai's generated config sets.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct EngineTuning {
    /// `numAnalysisThreads` — positions searched at once.
    pub analysis_threads: u16,
    /// `numSearchThreadsPerAnalysisThread` — MCTS threads within one position.
    pub search_threads: u16,
    /// `nnMaxBatchSize` — positions handed to the GPU in one batch.
    pub nn_max_batch_size: u16,
    /// `nnCacheSizePowerOfTwo` — the dominant memory use.
    pub nn_cache_size_power_of_two: u8,
}

/// Bytes one cached neural-net evaluation costs when ownership is included, per KataGo's
/// own estimate in `gtp_example.cfg`. mirai asks for ownership on nearly every query, so
/// this is the figure to quote at the user.
const CACHE_ENTRY_BYTES: u64 = 3 * 1024;

impl Default for EngineTuning {
    fn default() -> EngineTuning {
        EngineTuning {
            analysis_threads: 4,
            search_threads: 16,
            nn_max_batch_size: 64,
            nn_cache_size_power_of_two: 20,
        }
    }
}

impl EngineTuning {
    pub const MAX_ANALYSIS_THREADS: u16 = 64;
    pub const MAX_SEARCH_THREADS: u16 = 256;
    pub const MAX_BATCH_SIZE: u16 = 1024;
    pub const MIN_CACHE_POWER: u8 = 14;
    pub const MAX_CACHE_POWER: u8 = 24;

    /// Roughly how much memory the neural-net cache occupies once warm.
    pub fn cache_bytes(&self) -> u64 {
        CACHE_ENTRY_BYTES << self.nn_cache_size_power_of_two.min(40)
    }

    /// KataGo warns when the batch cannot cover every thread that may query at once.
    pub fn batch_covers_threads(&self) -> bool {
        u32::from(self.nn_max_batch_size)
            >= u32::from(self.analysis_threads) * u32::from(self.search_threads)
    }

    /// The config file text. The comments are for whoever opens the file wondering where
    /// it came from; only the keys matter.
    pub fn render(&self) -> String {
        format!(
            "\
# KataGo analysis config generated by mirai. Edit Preferences, not this file:
# it is rewritten whenever the engine settings change.
#
# Only the keys below are set. Search limits, rules, komi, board size and which
# outputs to include travel on each query; the reporting perspective and logging
# are forced on the command line; everything else is left at KataGo's own default.

# Positions searched at once.
numAnalysisThreads = {}
# MCTS threads within each of those positions.
numSearchThreadsPerAnalysisThread = {}
# Positions handed to the GPU in one batch. Wants to be at least the product above.
nnMaxBatchSize = {}

# Neural-net evaluation cache, a fixed-size table that fills and then evicts:
# 2^N entries of about 3 KiB each with ownership included, so it settles at
# roughly {} MiB. KataGo's own analysis default is 2^23, sized for a batch server
# rather than a desktop, which would settle 8x higher.
nnCacheSizePowerOfTwo = {}
",
            self.analysis_threads,
            self.search_threads,
            self.nn_max_batch_size,
            self.cache_bytes() / (1024 * 1024),
            self.nn_cache_size_power_of_two,
        )
    }

    /// Writes the config into `dir` and returns its path.
    ///
    /// The file name carries the settings, for two reasons. Profiles that tune differently
    /// must not race each other through one shared path — engines start concurrently, one
    /// per window — and an identical tuning then resolves to a byte-identical file that is
    /// left alone, so a config several windows share is never churned underneath a running
    /// KataGo. It reads the file once at startup and never again, but its reported
    /// `numAnalysisThreads` is read back out of it for [`crate::EngineDesc`].
    pub fn write_to(&self, dir: &Path) -> io::Result<PathBuf> {
        let path = dir.join(format!(
            "katago-analysis-a{}-s{}-b{}-c{}.cfg",
            self.analysis_threads,
            self.search_threads,
            self.nn_max_batch_size,
            self.nn_cache_size_power_of_two
        ));
        let text = self.render();
        if std::fs::read_to_string(&path).is_ok_and(|old| old == text) {
            return Ok(path);
        }
        std::fs::create_dir_all(dir)?;
        // Same tuning shares this path, and two windows may start together. The rename
        // publishes a complete file, so neither writer can leave KataGo a partial config.
        mirai_proto::atomic::write_atomic(&path, text.as_bytes())?;
        Ok(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The defaults are measured, not guessed: on a Radeon RX 6800, four positions in
    /// flight take the cost of switching nodes mid-search from 112 ms to 2.4 ms at no cost
    /// to single-position speed, and sixteen search threads is where the per-position
    /// curve flattens (8 → 16 buys 14%, 16 → 32 only 8% while adding tree contention).
    #[test]
    fn the_defaults_are_internally_consistent() {
        let t = EngineTuning::default();
        assert_eq!(t.analysis_threads, 4);
        assert_eq!(t.search_threads, 16);
        assert!(t.batch_covers_threads());
        assert!(t.nn_max_batch_size >= t.search_threads);
        // 2^20 entries at 3 KiB is 3 GiB: a desktop can spare it, and a cache miss only
        // costs a re-evaluation.
        assert_eq!(t.cache_bytes(), 3 * 1024 * 1024 * 1024);
    }

    #[test]
    fn a_batch_smaller_than_the_thread_product_is_reported() {
        let t = EngineTuning {
            nn_max_batch_size: 32,
            ..EngineTuning::default()
        };
        assert!(!t.batch_covers_threads());
    }

    #[test]
    fn the_rendered_config_carries_every_key_katago_demands() {
        let text = EngineTuning::default().render();
        for key in [
            "numAnalysisThreads",
            "numSearchThreadsPerAnalysisThread",
            "nnMaxBatchSize",
        ] {
            let line = text
                .lines()
                .find(|l| l.starts_with(key))
                .unwrap_or_else(|| panic!("{key} must be set: katago refuses to start without it"));
            assert!(line.contains('='), "{line:?} is not a key=value line");
        }
        // Anything mirai sends per query, or forces on the command line, must not be
        // frozen into the file as well.
        for absent in [
            "maxVisits",
            "reportAnalysisWinratesAs",
            "wideRootNoise",
            "logDir",
        ] {
            assert!(
                !text.lines().any(|l| l.starts_with(absent)),
                "{absent} does not belong in the generated config"
            );
        }
    }

    /// Two contracts at once: the same tuning resolves to the same untouched file, and two
    /// different tunings never share one — engines start concurrently, one per window, so
    /// a shared path would let one profile's config reach the other's KataGo.
    #[test]
    fn a_tuning_owns_its_own_file_and_rewrites_it_only_when_it_changes() {
        let dir = std::env::temp_dir().join("mirai-tuning-write-test");
        let _ = std::fs::remove_dir_all(&dir);
        let t = EngineTuning::default();

        let path = t.write_to(&dir).expect("write the generated config");
        let first = std::fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(t.write_to(&dir).unwrap(), path);
        assert_eq!(
            std::fs::metadata(&path).unwrap().modified().unwrap(),
            first,
            "an unchanged tuning must not rewrite the file"
        );

        let other = EngineTuning {
            search_threads: 8,
            ..t
        };
        let other_path = other.write_to(&dir).expect("write the second tuning");
        assert_ne!(other_path, path, "two tunings must not share one file");
        assert!(
            std::fs::read_to_string(&other_path)
                .unwrap()
                .contains("numSearchThreadsPerAnalysisThread = 8")
        );
        assert!(
            std::fs::read_to_string(&path)
                .unwrap()
                .contains("numSearchThreadsPerAnalysisThread = 16"),
            "the first config must survive the second untouched"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
